//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpirationDetail
    {
        public int ExpirationId { get; set; }
        public string ExpirationYear { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int SymbolId { get; set; }
    
        public virtual Symbol Symbol { get; set; }
    }
}
