//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Symbol()
        {
            this.ExpirationDetails = new HashSet<ExpirationDetail>();
        }
    
        public int SymbolId { get; set; }
        public string SymbolName { get; set; }
        public int DerivativeTypeId { get; set; }
    
        public virtual DerivativeType DerivativeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpirationDetail> ExpirationDetails { get; set; }
    }
}
